// @generated
// This file is @generated by prost-build.
/// Timestamp contains a cross-platform timestamp.
/// protobuf-go-lite:disable-json
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Timestamp {
    /// TimeUnixMs timestamp in unix milliseconds.
    #[prost(uint64, tag="1")]
    pub time_unix_ms: u64,
}
// @@protoc_insertion_point(module)
