// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/aperturerobotics/timestamp/timestamp.proto

/*
Package timestamp is a generated protocol buffer package.

It is generated from these files:
	github.com/aperturerobotics/timestamp/timestamp.proto

It has these top-level messages:
	Timestamp
*/
package timestamp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp contains a cross-platform timestamp.
type Timestamp struct {
	// TimeUnixMs timestamp in unix milliseconds.
	TimeUnixMs uint64 `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs" json:"time_unix_ms,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Timestamp) GetTimeUnixMs() uint64 {
	if m != nil {
		return m.TimeUnixMs
	}
	return 0
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "timestamp.Timestamp")
}

func init() {
	proto.RegisterFile("github.com/aperturerobotics/timestamp/timestamp.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2c, 0x48, 0x2d, 0x2a, 0x29, 0x2d, 0x4a, 0x2d,
	0xca, 0x4f, 0xca, 0x2f, 0xc9, 0x4c, 0x2e, 0xd6, 0x2f, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc,
	0x2d, 0x40, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0xe1, 0x02, 0x4a, 0xba, 0x5c,
	0x9c, 0x21, 0x30, 0x8e, 0x90, 0x02, 0x17, 0x0f, 0x48, 0x26, 0xbe, 0x34, 0x2f, 0xb3, 0x22, 0x3e,
	0xb7, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83, 0x25, 0x88, 0x0b, 0x24, 0x16, 0x9a, 0x97, 0x59, 0xe1,
	0x5b, 0x9c, 0xc4, 0x06, 0x36, 0xc0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x81, 0x99, 0x6b, 0x64,
	0x79, 0x00, 0x00, 0x00,
}
