// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: v0.7.0
// source: github.com/aperturerobotics/timestamp/timestamp.proto

package timestamp

import (
	fmt "fmt"
	io "io"
	strconv "strconv"
	strings "strings"

	protobuf_go_lite "github.com/aperturerobotics/protobuf-go-lite"
)

// Timestamp contains a cross-platform timestamp.
// protobuf-go-lite:disable-json
type Timestamp struct {
	unknownFields []byte
	// TimeUnixMs timestamp in unix milliseconds.
	TimeUnixMs uint64 `protobuf:"varint,1,opt,name=time_unix_ms,json=timeUnixMs,proto3" json:"timeUnixMs,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) GetTimeUnixMs() uint64 {
	if x != nil {
		return x.TimeUnixMs
	}
	return 0
}

func (m *Timestamp) CloneVT() *Timestamp {
	if m == nil {
		return (*Timestamp)(nil)
	}
	r := new(Timestamp)
	r.TimeUnixMs = m.TimeUnixMs
	if len(m.unknownFields) > 0 {
		r.unknownFields = make([]byte, len(m.unknownFields))
		copy(r.unknownFields, m.unknownFields)
	}
	return r
}

func (m *Timestamp) CloneMessageVT() protobuf_go_lite.CloneMessage {
	return m.CloneVT()
}

func (this *Timestamp) EqualVT(that *Timestamp) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if this.TimeUnixMs != that.TimeUnixMs {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Timestamp) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Timestamp)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (m *Timestamp) MarshalVT() (dAtA []byte, err error) {
	if m == nil {
		return nil, nil
	}
	size := m.SizeVT()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBufferVT(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Timestamp) MarshalToVT(dAtA []byte) (int, error) {
	size := m.SizeVT()
	return m.MarshalToSizedBufferVT(dAtA[:size])
}

func (m *Timestamp) MarshalToSizedBufferVT(dAtA []byte) (int, error) {
	if m == nil {
		return 0, nil
	}
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.unknownFields != nil {
		i -= len(m.unknownFields)
		copy(dAtA[i:], m.unknownFields)
	}
	if m.TimeUnixMs != 0 {
		i = protobuf_go_lite.EncodeVarint(dAtA, i, uint64(m.TimeUnixMs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Timestamp) SizeVT() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TimeUnixMs != 0 {
		n += 1 + protobuf_go_lite.SizeOfVarint(uint64(m.TimeUnixMs))
	}
	n += len(m.unknownFields)
	return n
}

func (x *Timestamp) MarshalProtoText() string {
	var sb strings.Builder
	sb.WriteString("Timestamp {")
	if x.TimeUnixMs != 0 {
		if sb.Len() > 11 {
			sb.WriteString(" ")
		}
		sb.WriteString("time_unix_ms: ")
		sb.WriteString(strconv.FormatUint(uint64(x.TimeUnixMs), 10))
	}
	sb.WriteString("}")
	return sb.String()
}

func (x *Timestamp) String() string {
	return x.MarshalProtoText()
}
func (m *Timestamp) UnmarshalVT(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return protobuf_go_lite.ErrIntOverflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Timestamp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Timestamp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnixMs", wireType)
			}
			m.TimeUnixMs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protobuf_go_lite.ErrIntOverflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeUnixMs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := protobuf_go_lite.Skip(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return protobuf_go_lite.ErrInvalidLength
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.unknownFields = append(m.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
