// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/timestamp/timestamp.proto (package timestamp, syntax proto3)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import { createMessageType, ScalarType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'timestamp'

/**
 * Timestamp contains a cross-platform timestamp.
 * protobuf-go-lite:disable-json
 *
 * @generated from message timestamp.Timestamp
 */
export interface Timestamp {
  /**
   * TimeUnixMs timestamp in unix milliseconds.
   *
   * @generated from field: uint64 time_unix_ms = 1;
   */
  timeUnixMs?: bigint
}

// Timestamp contains the message type declaration for Timestamp.
export const Timestamp: MessageType<Timestamp> = createMessageType({
  typeName: 'timestamp.Timestamp',
  fields: [
    { no: 1, name: 'time_unix_ms', kind: 'scalar', T: ScalarType.UINT64 },
  ] as readonly PartialFieldInfo[],
  packedByDefault: true,
})
